spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/documents/workspace/umpa/umpa;NON_KEYWORDS=USER
        username: sa
        password:
    jpa:
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
